# Generated by Django 5.2.1 on 2025-06-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Whiskey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('mocnist', models.IntegerField()),
                ('description', models.TextField()),
                ('release_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
