# Generated by Django 5.2.1 on 2025-06-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmain', '0002_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='type_car',
            field=models.CharField(choices=[('mechanics', 'механіка'), ('automatics', 'автоматика')], default='automatics', max_length=30),
        ),
    ]
