# Generated by Django 5.2.1 on 2025-06-18 08:26

import mmain.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmain', '0005_profile_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Men',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField(validators=[mmain.validators.check_age])),
            ],
        ),
    ]
